### ISSUE TITLE
Add IDE source code jumping

### ISSUE THREAD

**Issue by dereuromark** [gourmet/whoops#11]
See https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md

**Comment by LDSign** [comment]
Hi

Where to put the config (editor = true) mentioned in the Readme? And where can I specify the editor which will be used?

Thanks,
Frank

**Comment by dereuromark** [comment]
Resolved in https://github.com/dereuromark/cakephp-whoops - also see the wiki there.
